### ISSUE TITLE
redpwnctf: r1sc, given solution didn't work

### ISSUE THREAD

**Issue by klensy** [itsecgary/CTFs#1]
Hi.
Tried your solution and it didn't work, consumed about 8gb ram and crashed. What version of angr you used?
And this line https://github.com/itsecgary/CTFs/blob/1ddcc6c245efb9dbbe8b4fe231330fbc117dfa00/redpwnCTF%202020/r1sc/angry.py#L11 is no use, as you didn't pass it anywhere.

**Comment by itsecgary** [comment]
```
$ pip3 show angr
Name: angr
Version: 8.20.6.8
```

I didn't realize I had some unused code. Thanks for letting me know. I cleaned the script up and ran it again. It took my VM about 30 min, but it still worked. Is angr giving you a specific error?

**Comment by klensy** [comment]
Your vm ram size? Maybe mine not enough. With some alteration of your solution to give lower memory footprint, mine gives unsat solution.

**Comment by itsecgary** [comment]
I have 16 GB ram. I ran it again while monitoring the memory and it seems to be using up to 15.7 GB of it. I can see why yours would crash. I'm looking at some other less-expensive ways instead of angr. It seems like angr uses a lot of memory because of symbolic execution. There might be a way around that by limiting resources in python.

**Comment by klensy** [comment]
I've tried this solution, it uses not so many memory, but sadly, unsat
```python
#!/usr/bin/python

import angr

def main():
    p = angr.Project("./r1sc",
    )
    state = p.factory.entry_state(
        add_options={angr.options.LAZY_SOLVES},
    )
    
    simgr = p.factory.simulation_manager(state)
    simgr.explore(find=0x00401050, avoid=0x0040103b)
    return simgr.found[0].posix.dumps(0)

if __name__ == '__main__':
    import logging
    logging.getLogger('angr.sim_manager').setLevel(logging.DEBUG)
    print(main())
```

**Comment by itsecgary** [comment]
It seems I probably didn't take the right approach to this problem. Here is a different writeup for what looks to make more sense: https://ctf.harrisongreen.me/2020/redpwnctf/r1sc/

**Comment by klensy** [comment]
Found fast solution: about 1GB RAM and 2 minutes. Added few simple constraints: length and ascii range on chars:
```python
#!/usr/bin/python

import angr
import claripy
import binascii

def main():

    p = angr.Project("./r1sc",
        auto_load_libs=False,
    )
   
    input_chars = [claripy.BVS('input_%d' % i, 8) for i in range(0x30)]
    input  = claripy.Concat(*input_chars + [claripy.BVV(b'\n')])
    
    state = p.factory.full_init_state(
        add_options={
            angr.options.LAZY_SOLVES,
        },
        stdin=input,
        mode='symbolic_approximating',
    )
    
    for k in input_chars:
        state.solver.add(state.solver.And(k >= 0x20, k <= 0x7f))
        
    simgr = p.factory.simulation_manager(state)
    simgr.explore(find=0x401050, avoid=0x40103b)
    return simgr.found[0].posix.dumps(0)

if __name__ == '__main__':
    import logging
    logging.getLogger('angr.sim_manager').setLevel(logging.DEBUG)
    print(main())

```

**Comment by itsecgary** [comment]
Oh nice!! I ran it and it took me exactly 52 seconds. Nice find! Спасибо огромное.
